use_frameworks!

platform :ios, '9.0'

target 'WLToastView_Example' do
  
  pod 'WLToastView', :path => '../'
  
  pod 'MBProgressHUD'

  target 'WLToastView_Tests' do
    inherit! :search_paths

    
  end
end
